name: First-CI/CD-Action-Elastic-Beanstoalk

env:
  EB_PACKAGE_S3_BUCKET_NAME: "bkukl-github-actions"
  EB_APPLICATION_NAME      : "bkukl-github-application"
  EB_ENVIROMENT_NAME       : "Bkukl-github-application-env"
  DEPLOY_PACKAGE_NAME      : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME          : "eu-central-1"

on:
  push:
    branches: 
      - main

jobs:
  my-ci-part:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
    
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
  approval:
    needs: my-ci-part # Wait for the 'deploy' job to complete

    runs-on: ubuntu-latest

    steps:
      - name: Request approval
        id: approval
        uses: peter-evans/approval-action@v2.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Please approve the deployment"
          reviewers: bohdanhub # Add GitHub usernames of reviewers

      - name: Check approval status
        run: |
          echo "Approval status: ${{ steps.approval.outputs.approved }}"
          echo "Approved by: ${{ steps.approval.outputs.approved-by }}"
          # You can use the outputs from the approval action for further processing

