name: First-CI/CD-Action-Elastic-Beanstoalk

env:
  EB_PACKAGE_S3_BUCKET_NAME: "bkukl-github-actions"
  EB_APPLICATION_NAME      : "bkukl-github-application"
  EB_ENVIROMENT_NAME       : "Bkukl-github-application-env"
  DEPLOY_PACKAGE_NAME      : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME          : "eu-central-1"

on:
  push:
    branches: 
      - main

jobs:
  my-ci-part:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
    
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

